more fixes for packing

diff --git a/packages/rust/packaging b/packages/rust/packaging
--- a/packages/rust/packaging
+++ b/packages/rust/packaging
@@ -1,4 +1,4 @@
-set -e # exit immediately if a simple command exits with a non-zero status
+#set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 mkdir -p /var/vcap/packages/rust
 mkdir -p /var/vcap/data/rust
@@ -9,14 +9,17 @@ export HOME=/var/vcap
 export RUST_HOME=/var/vcap/packages/rust
 export RUST_DATA=/var/vcap/data/rust
 export COMPILE_HOME=`pwd`
+export TMP_RUST_DIR=/tmp/rust
 
-tar xvf rust/rust-*-x86_64-unknown-linux-gnu.tar.xz --strip-components=1 --exclude=rust-docs
+
+tar xvf rust/rust-*-x86_64-unknown-linux-gnu.tar.xz -C "${TMP_RUST_DIR}" --strip-components=1 --exclude=rust-docs
 cd rust*
 sudo ./install.sh --without=rust-docs
 
-cd ..
-rm -rf rust*
+cd /tmp
+rm -rf "${TMP_RUST_DIR}"
 
 
 
 cd $COMPILE_HOME
+#sleep 10000
